config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'
  
  
  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: :movie
  
  get '/actors' => 'actors#index'
  get '/actors/:id' => 'actors#show', as: :actor
  
  get '/search/:id' => 'movies#search', as: :search
  
  get '/add_movie/:id' => 'movies#add_movie', as: :add_movie
  
  get '/movies/categories/:id' => 'movies#categories', as: :categories
  

end

app/models/actor.rb
class Actor < ActiveRecord::Base
    has_many :parts 
    has_many :movies, through: :parts
    
    
    def character_in(movie)
        part = Part.where(actor_id: self.id, movie_id: movie.id).first
        part.character
    end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
    has_many :parts 
    has_many :actors, through: :parts
    
    def short_description
        self.plot[0...50]
    end
    
    
end

app/models/part.rb
class Part < ActiveRecord::Base
    belongs_to :movie 
    belongs_to :actor
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
    
    def index 
        @actors = Actor.all
    end
    
    def show
        @actor = Actor.find(params[:id])
        @movies = @actor.movies
        
        person = Tmdb::Person.detail(@actor.tmdb)
        
        @bio = person["biography"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  Tmdb::Api.key("8cb26e052ead7ca74eda6261beb93fd5")
  $configuration = Tmdb::Configuration.new
  Tmdb::Api.language("it")
  $base_url = $configuration.base_url
  $poster_size = "w342"
  $profile_size = "w185"
  
  def index
    movies = Tmdb::Movie.now_playing
    @movies = []
   
    movies.each do |movie|
      if Movie.where(tmdb: movie.id ).count > 0
        @movies.push(Movie.where(tmdb: movie.id ).first)
      else
        cast = Tmdb::Movie.casts(movie.id)
        posters = Tmdb::Movie.images(movie.id)['posters']
        if ((!posters.nil?) && (!cast.nil?))
          if (cast.any? && posters.any?)
            movie_par = Tmdb::Movie.detail(movie.id)
            @movie = Movie.new(movie_params(movie_par))
          else
            next
          end
        end
        if @movie.save!
          cast = Tmdb::Movie.casts(@movie.tmdb)
          if !cast.nil?
            add_cast(cast, @movie.id)
          end
        end
        @movies.push(@movie)     
      end
    end
  end
  
  def show
  	@movie = Movie.find(params[:id])
    @actors = @movie.actors
    trailer = Tmdb::Movie.trailers(@movie.tmdb)["youtube"]
    @imdb_link = "https://www.imdb.com/title/"+@movie.imdb unless @movie.imdb.nil?
    @trailer_url = "https://www.youtube.com/embed/"+trailer[0]["source"]+"?autoplay=0" unless !(trailer.size > 0)
  end
  
  
  def search
    @id = params[:search]
    @search = Tmdb::Search.new
    
    @search.resource('movie')
    @search.query(@id) 
    @movie_results = @search.fetch
  
    @movies = []
    
    @movie_results.each do |movie|
      cast = Tmdb::Movie.casts(movie["id"])
      posters = Tmdb::Movie.images(movie["id"])['posters']
      if ((!posters.nil?) && (!cast.nil?))
        if (cast.any? && posters.any?)
          @movies.push(movie)
        end
      end
    end
    render 'movie_results'
  end
  
  def add_movie
    
    tmdb_id = params[:id]
    
    # If a movie is already in our db then render the show page of that movie
    
    if Movie.where(tmdb: tmdb_id).count > 0 
      @movie = Movie.where(tmdb: tmdb_id).first
      @actors = @movie.actors
      
      render 'show'
    else
    
    # If it's not, then we retrieve the movie's informations and store it in the db
    
      movie_par = Tmdb::Movie.detail(tmdb_id)
      
      
      @movie = Movie.new(movie_params(movie_par))
      
      
      if @movie.save!
        trailer_hash = Tmdb::Movie.trailers(tmdb_id)
        if !trailer_hash.nil?
          if trailer_hash["youtube"].size > 0
            @trailer_url = "https://www.youtube.com/embed/"+Tmdb::Movie.trailers(tmdb_id)["youtube"][0]["source"]+"?autoplay=0"
          end
        end
       
        cast = Tmdb::Movie.casts(tmdb_id)
        
        if !cast.nil?
          add_cast(cast, @movie.id)
        end
      end
      @actors = @movie.actors
      render :show
    end
  end
  
  
  def categories
    @categorie = params[:id].capitalize
    case params[:id]
    when "upcoming"
      movies = Tmdb::Movie.upcoming
    when "top_rated"
      movies = Tmdb::Movie.top_rated
    when "popular"
      movies = Tmdb::Movie.popular
    end
    @movies = []
    movies.each do |movie|
      if Movie.where(tmdb: movie.id ).count > 0
        @movies.push(Movie.where(tmdb: movie.id ).first)
        
      else
        cast = Tmdb::Movie.casts(movie.id)
        posters = Tmdb::Movie.images(movie.id)['posters']
        if ((!posters.nil?) && (!cast.nil?))
          if (cast.any? && posters.any?)
            movie_par = Tmdb::Movie.detail(movie.id)
            @movie = Movie.new(movie_params(movie_par))
          else
            next
          end
        end
        if @movie.save!
          cast = Tmdb::Movie.casts(movie.id)
          
          if !cast.nil?
            add_cast(cast, @movie.id)
          end
        end
        @movies.push(@movie)
      end
      @movies.sort! { |a,b| b.rating <=> a.rating }
    end
    
  end
  
  private 
  
    def movie_params(movie)
      
      title = movie["title"]
      plot = movie["overview"]
      release_year = movie["release_date"]
      if !movie["vote_average"].nil?
        rating = movie["vote_average"]/2
      else
        rating = 2.5
      end
      imdb = movie["imdb_id"]
      tmdb = movie["id"]
      poster_hash = Tmdb::Movie.images(tmdb)['posters'][0]['file_path']
      
      tagline = Tmdb::Movie.detail(tmdb)["tagline"]
      
      poster_path = $base_url+$poster_size+poster_hash unless poster_hash.nil?
      
      
      hash = { "title" => title, "release_year" => release_year, "image" => poster_path, "plot" => plot,  "tmdb"=> tmdb ,"imdb" => imdb, "rating" => rating, "tagline" => tagline }
      return hash
    end
    
    def actor_params
      { "name" => "test", "character" => "test"}
    end
    
    
    def add_cast(cast, movie_id)
      @movie = Movie.find(movie_id)  
# We check if the cast size is greater than 8 to have max 8 actors per film
      if cast.size > 7
        cast_size = 7
      else
        cast_size = cast.size
      end
      for i in 0..cast_size
        if !cast[i].nil?
          
# If an actor is already in our DB we don't add it again, but just push it into the @actors array
          actor = Actor.where(name: cast[i]["name"])
          if actor.any? 
            @movie.actors << actor.first
            Part.where(actor_id: actor.first.id, movie_id: @movie.id).first.update(character: cast[i]["character"])
          else
            actor = Actor.new(actor_params)
            if !cast[i]["profile_path"].nil?
                profile_image = $base_url+$profile_size+cast[i]["profile_path"]
            else
              profile_image = nil
            end
            
            if actor.save!
              actor.update(name: cast[i]["name"], character: cast[i]["character"], image: profile_image, tmdb: cast[i]["id"])
              @movie.actors << actor
              Part.where(actor_id: actor.id, movie_id: @movie.id).first.update(character: cast[i]["character"])
            end
          end
        end
      end
      @movie
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    def random_movie
        movie_list = []
        last = Movie.last.id
        val = rand(last-50..last)
        i=0
        while i<4
            if !Movie.exists?(val)
                val = rand(last-50..last)
                next
            elsif movie_list.include?(Movie.find(val))
                val = rand(last-50..last)
                next
            else
                movie_list.push(Movie.find(val))
                i+=1
            end
        end
        movie_list
        
    end
end

app/views/actors/index.html.erb
<script type="text/javascript">
			$(window).load(function() {
				$(".loader").stop().fadeOut("slow");
			})	
		</script>
   	<div class="loader"></div>

<div class="main actor-index">
    <div class="container">
        <div class="row">
		    <% @actors.each do |f| %>
                <div class="actor col-xs-3">
                    <%= image_tag f.image %>
                    <h3> <%= f.name %> </h3>
                    <%= link_to "See more" , actor_path(f) %>
                    <p> <%= f.bio %> </p>
                </div>
            <% end %> 
        </div>
    </div>
</div>

app/views/actors/show.html.erb
<div class="main actor-show">
    <div class="container">
        
        <!-- Display an actor's info here -->
        <div class="actor row" style="height:auto" >
            <div class="col-sm-4"> <%= image_tag @actor.image %> </div>
            <div class="col-sm-8" >
                <div class="info" style="width:auto">
                    <h3 class="actor-name"> <%= @actor.name %> </h3>
                    <p class="actor-bio" style="padding:5em 5em 5em 0"> <%= @bio %></p>
                </div>
            </div>
        </div>
        
    <div class="movies row" >
            <h2>Movies</h2>
            <% @movies.each do |f| %>
              <div class="movie">
                <%= link_to image_tag(f.image), movie_path(f) %>
                <h3 class="movie-title"> <%= f.title %> </h3>
                <p class="movie-release-year"> <%= f.release_year %> </p>
                <p class="text">as: <%= @actor.character_in(f) %></p>
                <p class="movie-plot">
                    <% if f.plot.length < 120 %>
                        <%= f.plot %> 
                    <% else %>
                        <%= f.plot[0...120]+" . . ." %>
                        <%= link_to "Read more", movie_path(f) %>
                    <% end %>
                </p>
              </div>
            <% end %>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Base</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'> 
    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' rel='stylesheet' type='text/css'>
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
		
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	
   	
		
		<div class="loader">
	    <span class="ball"></span>
	    <span class="ball2"></span>
	    <ul>
	        <li></li><li></li><li></li><li></li><li></li>
	    </ul>
		</div>
    
		<nav class="navbar navbar-inverse navbar-fixed-top header" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
				  <li><h1 id="title">Movie Base</h1></li>
					<li style="padding-left:2em;"><%= link_to "Movies", movies_path, :class => "custom-link" %></a></li>
					<li><%= link_to "Actors", actors_path , :class => "custom-link" %></li>
					<li class="dropdown">
					  	<%= link_to 'Categories <b class="caret"></b>'.html_safe, "#", :id => 'dropdownMenu1', :'data-toggle' => 'dropdown', :'aria-haspopup' => "true" , :class => 'dropdown-toggle custom-link' %>
					  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
					    <li><%= link_to "Upcoming" , categories_path("upcoming")%></li>
							<li><%= link_to "Popular" , categories_path("popular")%></li>
							<li><%= link_to "Top Rated", categories_path("top_rated") %></li>
					    <li role="separator" class="divider"></li>
					    <li><a href="#">TV Shows</a></li>
					  </ul>
					</li>
				</ul>
				
				
				<div class="navbar-form pull-right" role="search" >
				  <div class="input-group">
            <%= form_tag search_path(:search), :method => 'get' , :style => "display:inline" do %>
              <%= text_field_tag :search, params[:search] , placeholder: "Search" , class:"form-control", style:"width: 200px; margin-right: 35px, border: 1px solid black; background-color: #e5e5e5;float:left"%>
              <span class="input-group-btn pull-right" style="float:right">
                <%= button_tag(type: "submit" , class:"btn btn-default")  do %>
                  <i class="glyphicon glyphicon-search"><span class="sr-only">Search</span></i>
                <% end %>
                <button type="reset" class="btn btn-default">
  								<span class="glyphicon glyphicon-remove">
  									<span class="sr-only">Close</span>
  								</span>
							  </button>
              </span>
					  <% end %>
          </div>
          
        </div>
        
				
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
  <div id="wrap">
      <%= yield %>
  </div>
  <footer class="footer" style="background-color:darkgray;">
      <p class="text-right">
        <img src="https://assets.tmdb.org/images/logos/var_2_0_PoweredByTMDB_Blk_Bree.png" alt="V2.0 (PNG)" >
      </p>
  </footer>
  
  
  <script type="text/javascript">
  
  // Javascript / JQuery for loading animation
  
			$(document).ready(function() {
				$(".loader").fadeOut("slow");
			})	
			var myEvent = window.attachEvent || window.addEventListener;
			var chkevent = window.attachEvent ? 'onbeforeunload' : 'beforeunload'; /// make IE7, IE8 compitable

            myEvent(chkevent, function(e) { // For >=IE7, Chrome, Firefox
                $(".loader").fadeIn(100);
            });
	</script>
  </body>
</html>

app/views/movies/categories.html.erb
<div class="main">
  <div class="container">
   <h2><%= @title %></h2>
    <div class="row">
      <% @movies.each do |f| %>
      <div class="col-md-3">
        <div class="movie">
        <%= image_tag f.image %>
        <h3> <%= f.title %> </h3>
        <p> <%= f.release_year %> </p>
        <%= link_to "Learn more", movie_path(f) %>
        </div>
    </div>
  <% end %>
      
  </div>
</div>

app/views/movies/index.html.erb
<!--
<div class="hero">
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href="#">Read More</a>
  </div>
</div>
-->

<div id="wrapper jumbotron">
  <h2 style="text-align:center;color:#0393ff; margin:0 auto; padding-top:30px">POPULAR MOVIES<hr></h2>
  <div id="content" class="row" style ="margin:0 2em;">
    
    
    <div class="col-md-6">
    <ul id="movieposters">
        <% movie_list = random_movie %>
        <% movie1 = movie_list[0] %>
  			<li>
  				<img src='<%= movie1.image %>' alt="X-Men" width="300px" height="450px"/>
  				<div class="movieinfo">
  					<h3><%= movie1.title %></h3>
  					<p><%= movie1.tagline %> </p>
  					<%= link_to "More info" , movie_path(movie1) %>
  				</div>
  			</li>
  			<% movie2 = movie_list[1] %>
  			<li>
  				<img src='<%= movie2.image %>' alt="X-Men" width="300px" height="450px" />
  				<div class="movieinfo">
  					<h3><%= movie2.title %></h3>
  					<p><%= movie2.tagline %> </p>
  					<%= link_to "More info" , movie_path(movie2) %>
  				</div>
  			</li>
  	</ul>
  	</div>
  	<div class="col-md-6">
  	<ul id="movieposters_right">
  			<% movie3 = movie_list[2] %>
  			<li>
  				<img src='<%= movie3.image %>' alt="X-Men" width="300px" height="450px"  />
  				<div class="movieinfo_right ">
  					<h3><%= movie3.title %></h3>
  					<p><%= movie3.tagline %> </p>
  					<%= link_to "More info" , movie_path(movie3) %>
  				</div>
  			</li>
  			<% movie4 = movie_list[3] %>
  			<li>
  				<img src='<%= movie4.image %>' alt="X-Men" width="300px" height="450px" />
  				<div class="movieinfo_right">
  					<h3><%= movie4.title %></h3>
  					<p><%= movie4.tagline %> </p>
  					<%= link_to "More info" , movie_path(movie4) %>
  				</div>
  			</li>
			
		</ul>
		</div>
	</div>
</div>
<hr>
<div class="main">
  <div class="container">
   <h2>In Theaters</h2>
    <div class="row">
      <% @movies.each do |f| %>
      <div class="col-md-3">
        <div class="movie">
        <%= image_tag f.image %>
        <h3> <%= f.title %> </h3>
        <p> <%= f.release_year %> </p>
        <%= link_to "Learn more", movie_path(f) %>
        </div>
    </div>
  <% end %>
      
  </div>
</div>

app/views/movies/movie_results.html.erb
<div class="container">
    
        <h1 class="header-text row">Search Results
        <hr>
        </h1>
        
        
    
        <% if @movies.count>0 %>
            <% @movies.each do |f| %>
                <div class="row" style="width:auto;display:block;margin-left:0;margin-right:0">
                    <h3 >
                        <%= link_to f["title"], add_movie_path(f["id"]), :class => 'custom-link' %>
                    </h3>
                </div>
            <% end %>
        <% else %>
           
            <h1>No Results</h1> 
            <p>Your search produced 0 results.</p> 
              
           
        <% end %>
    </div>
</div>

app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie row">
      
      <!-- Display the movie's info here -->
      <div class="row" style="height:auto;padding-bottom:2em;">
        <div class="col-sm-4">
          <%= image_tag @movie.image %>
        </div>
        <div class="col-sm-8">
          <div class="info" style="width:100%;margin-left:0.5em">
          <h3 class="movie-title"> <%= @movie.title %>  </h3></br>
          <p class="movie-release-year text-right"> <%= @movie.release_year %> </p>
          <p class="movie-plot" style="font-size:15px;"> <%= @movie.plot %> 
            <div style="padding-top:2em; color:#0393ff" ><%= link_to "IMDB" , @imdb_link , :class => "custom-link", :target => "_blank" %> Rating:<span class="stars pull-right" id="stars" ><%= @movie.rating %></span></div>
          </p>
          </div>
        </div>
      </div>
    </div>
    <% if !@trailer_url.nil? %>
    <h2 class="header-text row" style="margin: 0 auto">Trailer
        <hr>
    </h1>
    <div class="container" style="display:block;max-width:930px">
      <div align="center" class="row embed-responsive embed-responsive-16by9">
      <iframe width="400" height="315" src='<%= @trailer_url %>'>
      </iframe>
      </div>
    </div>
    <% end %>
  
  </div>
  <div class="container">
    <h2>Cast</h2>
    <div class="cast row">
      <% @actors.each do |f| %>
        <div class="actor col-md-3">
      <!-- Display each actor's info here -->
          <% if f.image.nil? %>
            <%= link_to image_tag('https://brocku.ca/sites/default/files/noImageAvailable%20icon_10.jpg'), actor_path(f) %>
          <% else %>
            <%= link_to image_tag(f.image) , actor_path(f) %>
          <% end %>
          <h3 class="actor-name"> <%= f.name %> </h3>
          <p class="actor-bio">as: <%= f.character_in(@movie) %> </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
 $.fn.stars = function() {
    return this.each(function(i,e){$(e).html($('<span/>').width($(e).text()*16));});
};

$(document).ready($('#stars').stars());
</script>